[package]
name = "black-box"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
bincode = "1.3"
time = { version = "0.3", features = ["serde"] }

